
CREATE TABLE cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    color TEXT NOT NULL,
    manufacture_year INTEGER NOT NULL,
    license_plate TEXT NOT NULL,
    registration_date DATE,
    imported BOOLEAN NOT NULL DEFAULT FALSE,
    owner_id BIGINT NOT NULL,

    CONSTRAINT pk_cars PRIMARY KEY (id),
    CONSTRAINT uq_cars_license_plate UNIQUE (license_plate),
    CONSTRAINT fk_cars_owner
        FOREIGN KEY (owner_id)
            REFERENCES customers (id)
);
